# Default Config

toggle_hotkey = "ALT+SPACE"
placeholder = "Search apps, files and commands…"
search_url = "https://google.com/search?q=%s"
show_trayicon = true
shells = []
clipboard_hotkey = "SUPER+SHIFT+C"
screenshot_hotkey = "SUPER+SHIFT+S"
recorder_hotkey = "SUPER+SHIFT+R"

[buffer_rules]
clear_on_hide = true
clear_on_enter = true

[theme]
text_color = [0.95, 0.95, 0.96]
background_color = [0.09, 0.09, 0.09]
# Background opacity should / can be omitted from 0.4.5 onwards, 
# as rustcast doesn't support custom opacity's anymore, 
# this field will have no effect on rustcast
background_opacity = 0.0
blur = false
show_icons = true
show_scroll_bar = true

[recorder]
fps = 30
aspect_lock = true
output_width = 1920
output_height = 1080
keep_recording_when_minimized = true
show_cursor = true
record_audio = false
show_indicator = true
picture_in_picture = false
output_dir = "~/Videos/RustCast"
